/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.StavkaKartona;
import javax.swing.JTextField;

/**
 *
 * @author Emilija
 */
public class DetaljiIzabranogKartonaForma extends javax.swing.JFrame {

    /**
     * Creates new form DetaljiIzabranogKartonaForma
     */
    public DetaljiIzabranogKartonaForma(StavkaKartona sk) {
        initComponents();
    }

    public JTextField getjTextFieldStatus() {
        return jTextFieldStatus;
    }

    public void setjTextFieldStatus(JTextField jTextFieldStatus) {
        this.jTextFieldStatus = jTextFieldStatus;
    }
    
    public JTextField getjTextFieldAnestezija() {
        return jTextFieldAnestezija;
    }

    public void setjTextFieldAnestezija(JTextField jTextFieldAnestezija) {
        this.jTextFieldAnestezija = jTextFieldAnestezija;
    }

    public JTextField getjTextFieldDDokumentacija() {
        return jTextFieldDDokumentacija;
    }

    public void setjTextFieldDDokumentacija(JTextField jTextFieldDDokumentacija) {
        this.jTextFieldDDokumentacija = jTextFieldDDokumentacija;
    }

    public JTextField getjTextFieldDatumArhiviranja() {
        return jTextFieldDatumArhiviranja;
    }

    public void setjTextFieldDatumArhiviranja(JTextField jTextFieldDatumArhiviranja) {
        this.jTextFieldDatumArhiviranja = jTextFieldDatumArhiviranja;
    }

    public JTextField getjTextFieldDijagnoza() {
        return jTextFieldDijagnoza;
    }

    public void setjTextFieldDijagnoza(JTextField jTextFieldDijagnoza) {
        this.jTextFieldDijagnoza = jTextFieldDijagnoza;
    }

    public JTextField getjTextFieldIntervencija() {
        return jTextFieldIntervencija;
    }

    public void setjTextFieldIntervencija(JTextField jTextFieldIntervencija) {
        this.jTextFieldIntervencija = jTextFieldIntervencija;
    }

    public JTextField getjTextFieldNaznake() {
        return jTextFieldNaznake;
    }

    public void setjTextFieldNaznake(JTextField jTextFieldNaznake) {
        this.jTextFieldNaznake = jTextFieldNaznake;
    }

    public JTextField getjTextFieldTerapija() {
        return jTextFieldTerapija;
    }

    public void setjTextFieldTerapija(JTextField jTextFieldTerapija) {
        this.jTextFieldTerapija = jTextFieldTerapija;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldDatumArhiviranja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDijagnoza = new javax.swing.JTextField();
        jTextFieldTerapija = new javax.swing.JTextField();
        jTextFieldNaznake = new javax.swing.JTextField();
        jTextFieldAnestezija = new javax.swing.JTextField();
        jTextFieldIntervencija = new javax.swing.JTextField();
        jTextFieldDDokumentacija = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datum arhiviranja (dd.MM.yyyy) : ");

        jLabel2.setText("Dijagnoza :");

        jLabel3.setText("Terapija : ");

        jLabel4.setText("Naznake : ");

        jLabel5.setText("Anestezija : ");

        jLabel6.setText("Intervencija : ");

        jLabel7.setText("Dodatna dokumentacija : ");

        jLabel8.setText("Status :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDatumArhiviranja)
                    .addComponent(jTextFieldDijagnoza)
                    .addComponent(jTextFieldTerapija)
                    .addComponent(jTextFieldNaznake)
                    .addComponent(jTextFieldAnestezija)
                    .addComponent(jTextFieldIntervencija)
                    .addComponent(jTextFieldDDokumentacija)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDatumArhiviranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNaznake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAnestezija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldIntervencija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDDokumentacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldAnestezija;
    private javax.swing.JTextField jTextFieldDDokumentacija;
    private javax.swing.JTextField jTextFieldDatumArhiviranja;
    private javax.swing.JTextField jTextFieldDijagnoza;
    private javax.swing.JTextField jTextFieldIntervencija;
    private javax.swing.JTextField jTextFieldNaznake;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTerapija;
    // End of variables declaration//GEN-END:variables
}
