/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import cordinator.Cordinator;
import domen.MedicinskiRadnik;
import domen.Pacijent;
import domen.StatusKartona;
import domen.StavkaKartona;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author Emilija
 */
public class KreirajKartonForma extends javax.swing.JFrame {

    /**
     * Creates new form KreirajKarton
     */
    public KreirajKartonForma() {
        initComponents();
    }

    

    public JButton getjButtonKreiraj() {
        return jButtonKreiraj;
    }

    public void setjButtonKreiraj(JButton jButtonKreiraj) {
        this.jButtonKreiraj = jButtonKreiraj;
    }

    public JButton getjButtonSacuvaj() {
        return jButtonSacuvaj;
    }

    public void setjButtonSacuvaj(JButton jButtonSacuvaj) {
        this.jButtonSacuvaj = jButtonSacuvaj;
    }

    

    public JComboBox<MedicinskiRadnik> getjComboBoxMradnik() {
        return jComboBoxMradnik;
    }

    public void setjComboBoxMradnik(JComboBox<MedicinskiRadnik> jComboBoxMradnik) {
        this.jComboBoxMradnik = jComboBoxMradnik;
    }

    public JComboBox<Pacijent> getjComboBoxPacijent() {
        return jComboBoxPacijent;
    }

    public void setjComboBoxPacijent(JComboBox<Pacijent> jComboBoxPacijent) {
        this.jComboBoxPacijent = jComboBoxPacijent;
    }

    public JComboBox<StatusKartona> getjComboBoxStatus() {
        return jComboBoxStatus;
    }

    public void setjComboBoxStatus(JComboBox<StatusKartona> jComboBoxStatus) {
        this.jComboBoxStatus = jComboBoxStatus;
    }

    public JTextField getjTextFieldDatumOtvaranja() {
        return jTextFieldDatumOtvaranja;
    }

    public void setjTextFieldDatumOtvaranja(JTextField jTextFieldDatumOtvaranja) {
        this.jTextFieldDatumOtvaranja = jTextFieldDatumOtvaranja;
    }

    public JTable getjTableIntervencije() {
        return jTableIntervencije;
    }

    public void setjTableIntervencije(JTable jTableIntervencije) {
        this.jTableIntervencije = jTableIntervencije;
    }

    public JTextField getjTextFieldAnestezija() {
        return jTextFieldAnestezija;
    }

    public void setjTextFieldAnestezija(JTextField jTextFieldAnestezija) {
        this.jTextFieldAnestezija = jTextFieldAnestezija;
    }

    public JTextField getjTextFieldDijagnoza() {
        return jTextFieldDijagnoza;
    }

    public void setjTextFieldDijagnoza(JTextField jTextFieldDijagnoza) {
        this.jTextFieldDijagnoza = jTextFieldDijagnoza;
    }

    public JTextField getjTextFieldDodatnaDokumentacija() {
        return jTextFieldDodatnaDokumentacija;
    }

    public void setjTextFieldDodatnaDokumentacija(JTextField jTextFieldDodatnaDokumentacija) {
        this.jTextFieldDodatnaDokumentacija = jTextFieldDodatnaDokumentacija;
    }

    public JTextField getjTextFieldKorMaterijal() {
        return jTextFieldKorMaterijal;
    }

    public void setjTextFieldKorMaterijal(JTextField jTextFieldKorMaterijal) {
        this.jTextFieldKorMaterijal = jTextFieldKorMaterijal;
    }

    public JTextField getjTextFieldNaznaka() {
        return jTextFieldNaznaka;
    }

    public void setjTextFieldNaznaka(JTextField jTextFieldNaznaka) {
        this.jTextFieldNaznaka = jTextFieldNaznaka;
    }

    public JTextField getjTextFieldTerapija() {
        return jTextFieldTerapija;
    }

    public void setjTextFieldTerapija(JTextField jTextFieldTerapija) {
        this.jTextFieldTerapija = jTextFieldTerapija;
    }

    public JTextField getjTextFieldDatumIntervencije() {
        return jTextFieldDatumIntervencije;
    }

    public void setjTextFieldDatumIntervencije(JTextField jTextFieldDatumIntervencije) {
        this.jTextFieldDatumIntervencije = jTextFieldDatumIntervencije;
    }
    

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPacijent = new javax.swing.JComboBox<>();
        jComboBoxMradnik = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDatumOtvaranja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIntervencije = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButtonDodajIntervenciju = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDijagnoza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldKorMaterijal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTerapija = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNaznaka = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAnestezija = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDodatnaDokumentacija = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDatumIntervencije = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pacijent : ");

        jLabel2.setText("Medicinski radnik : ");

        jLabel4.setText("Datum otvaranja (dd.MM.yyyy) : ");

        jLabel3.setText("Status : ");

        jComboBoxStatus.setModel(new DefaultComboBoxModel(StatusKartona.values())
        );
        jComboBoxStatus.setSelectedIndex(-1);

        jButtonKreiraj.setText("Kreiraj");

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jTableIntervencije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableIntervencije);

        jLabel5.setText("Intervencije : ");

        jButtonDodajIntervenciju.setText("Dodaj intervenciju ");
        jButtonDodajIntervenciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajIntervencijuActionPerformed(evt);
            }
        });

        jLabel6.setText("Dijagnoza : ");

        jLabel7.setText("Korisceni materijal : ");

        jLabel8.setText("Terapija : ");

        jLabel9.setText("Naznaka : ");

        jLabel10.setText("Anestezija : ");

        jLabel11.setText("Dodatna dokumentacija : ");

        jLabel12.setText("Datum intervencije(dd.MM.yyyy) : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonKreiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvaj)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldKorMaterijal)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(jComboBoxPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxMradnik, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDatumOtvaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAnestezija, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDodatnaDokumentacija, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldDatumIntervencije, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNaznaka, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addComponent(jButtonDodajIntervenciju)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMradnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDatumOtvaranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDodajIntervenciju))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldKorMaterijal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldNaznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldAnestezija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldDodatnaDokumentacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldDatumIntervencije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKreiraj)
                    .addComponent(jButtonSacuvaj))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
       
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonDodajIntervencijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajIntervencijuActionPerformed
        Cordinator.getInstance().otvoriDodajIntervencijuForma();
    }//GEN-LAST:event_jButtonDodajIntervencijuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajIntervenciju;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<MedicinskiRadnik> jComboBoxMradnik;
    private javax.swing.JComboBox<Pacijent> jComboBoxPacijent;
    private javax.swing.JComboBox<StatusKartona> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIntervencije;
    private javax.swing.JTextField jTextFieldAnestezija;
    private javax.swing.JTextField jTextFieldDatumIntervencije;
    private javax.swing.JTextField jTextFieldDatumOtvaranja;
    private javax.swing.JTextField jTextFieldDijagnoza;
    private javax.swing.JTextField jTextFieldDodatnaDokumentacija;
    private javax.swing.JTextField jTextFieldKorMaterijal;
    private javax.swing.JTextField jTextFieldNaznaka;
    private javax.swing.JTextField jTextFieldTerapija;
    // End of variables declaration//GEN-END:variables

    public void sacuvajActionLisener(ActionListener actionListener) {
         for (ActionListener al : jButtonSacuvaj.getActionListeners()) {
        jButtonSacuvaj.removeActionListener(al);
    }
        jButtonSacuvaj.addActionListener(actionListener);
    }

    

    public void kreirajLActionLisener(ActionListener actionListener) {
        for (ActionListener al : jButtonKreiraj.getActionListeners()) {
        jButtonKreiraj.removeActionListener(al);
    }
        jButtonKreiraj.addActionListener(actionListener);
    }
}
